   services:
     - type: web
       name: bottle-app
       env: python
       buildCommand: "pip install -r requirements.txt"
       startCommand: "python App/bottle_app.py"
       envVars:
         - key: PORT
           value: "10000"
       port: 10000